config_version : 0

version:  1.7.9

name: rez

uuid: 2f31e00b-279e-486c-a804-49131fa7c7bf

authors:
- tzhu

package_wiki: http://some_web_link

release_info: >
 updated with ability to source dev 
 
description: >
 Rez installation
 
commands:
- export PYTHONPATH=!ROOT!/python:$PYTHONPATH
- export PATH=!ROOT!/bin:$PATH

